### ISSUE TITLE
Plots.py is giving key error when no transaction has been done

### ISSUE THREAD

**Issue by shrutiv123** [smanishs175/WalletBuddy#13]
When owe() function is called in plots.py it throws a key error for 'transactions'.

Below is the error :
File "/root/dev-integration/main/plots.py", line 89, in owe
    for j in expense_dict[chat_id]['transactions']:
KeyError: 'transactions'

**Comment by pjhamb** [comment]
It was due to not loading config files by running config func. Resolved by putting this in plots.py
